---
title: "Intro to R for Plant Pathology"
---

This introduction to R for plant pathology was originally written as a workshop by Drs. Sydney E. Everhart and Zhian N. Kamvar, and modified to the current form for the 2018 course PLPT 802: Ecology & Management of Plant Pathogens. We will first cover the basics of using R and then learn how to analyze data that we collected during class from leaf images. 

Before class, make sure to complete the [installation instructions].

## Goals

As a result of taking this workshop you should be able to:

 - find, download, and load necessary packages for analysis
 - load tabular data into R
 - understand the basics of data manipulation in R
 - know what a data frame, vector, and function are
 - summarize data
 - visualize data
 - troubleshoot commmon problems

## About
The source code for this website and analyses can be found at: 
https://github.com/everhartlab/IntroR-for-PLPT802.

[installation instructions]: https://everhartlab.github.io/IntroR-for-PLPT802/installation.html